# Generated by Django 5.2.8 on 2025-12-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
